# Generated by Django 2.2.7 on 2019-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
